server:
  servlet:
    context-path: /batch

spring:
  # 로컬환경에서 인텔리제이로 디버깅 모드 실행 위한 기본 프로파일 설정
  profiles:
    active: local

# 다른 서비스에서 배치 api 호출 할 때 필요한 헤더 키
internal-api:
  header-secret: eiwoxc325kok07Acd

# 데이터 수집 api
# https://developers.naver.com/docs/serviceapi/search/news/news.md#%EB%89%B4%EC%8A%A4
naver-api:
  headers:
    - X-Naver-Client-Id # client-id 헤더명
    - X-Naver-Client-Secret # secret 헤더명
  client-id: clientid를넣으세요
  secret:  secretkey를넣으세요
# https://www.googleapis.com/customsearch/v1?key={apikey}&cx={cx}&q={query}&start={start}&num={num}
google-api:
  key: googleapi키를넣으세요 # API KEY
  cx: 검색엔진id를설정하고넣으세요 # 검색 엔진 ID
  header-referer: http://localhost:8080