spring:
  datasource:
    batch:
      url: jdbc:mysql://mysqldb:3306/news_batch?useUnicode=true&characterEncoding=UTF-8
      username: batch_user
      password: bdb!user432Q
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
        idle-timeout: 600000
        initialization-fail-timeout: 10000
        connection-timeout: 50000 #(ms)
        max-lifetime: 1800000
        leak-detection-threshold: 15000
        pool-name: BatchHikariPool
    news:
      url: jdbc:mysql://mysqldb:3306/news_api?useUnicode=true&characterEncoding=UTF-8
      username: news_user
      password: ndb!user432Q
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 600000
        initialization-fail-timeout: 10000
        connection-timeout: 30000 #(ms)
        max-lifetime: 1800000
        pool-name: NewsHikariPool

  jpa:
    open-in-view: false